listener 1883
allow_anonymous true
connection_messages true
log_dest file c:/Users/UNI-PIPC/Documents/Development/Work/project-mosquitto-in-fastapi/logs/mosquitto.log
log_type all
message_size_limit 51200